// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugtqlzamyuvxfsjdrwxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndHFsemFteXV2eGZzamRyd3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTU3MDUsImV4cCI6MjA2MzMzMTcwNX0.CQwz8qQnrCZ1wC0vfcmp3T4EA2_aJIxjLBd3Oqh_Wv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);